// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka-sink-collector.proto

package sh.batch.services;

/*-
 * #%L
 * sink-connector
 * %%
 * Copyright (C) 2020 Batch.sh
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

public interface AddKafkaSinkRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.AddKafkaSinkRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 num_records_processed = 1;</code>
   */
  long getNumRecordsProcessed();

  /**
   * <code>.events.Status status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>.events.Status status = 2;</code>
   */
  sh.batch.events.ResponseStatus.Status getStatus();
  /**
   * <code>.events.Status status = 2;</code>
   */
  sh.batch.events.ResponseStatus.StatusOrBuilder getStatusOrBuilder();
}
