// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kafka-sink-collector.proto

package sh.batch.services;

public interface AddKafkaSinkRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.AddKafkaSinkRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .records.KafkaSinkRecord records = 1;</code>
   */
  java.util.List<sh.batch.events.records.Kafka.KafkaSinkRecord> 
      getRecordsList();
  /**
   * <code>repeated .records.KafkaSinkRecord records = 1;</code>
   */
  sh.batch.events.records.Kafka.KafkaSinkRecord getRecords(int index);
  /**
   * <code>repeated .records.KafkaSinkRecord records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .records.KafkaSinkRecord records = 1;</code>
   */
  java.util.List<? extends sh.batch.events.records.Kafka.KafkaSinkRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .records.KafkaSinkRecord records = 1;</code>
   */
  sh.batch.events.records.Kafka.KafkaSinkRecordOrBuilder getRecordsOrBuilder(
      int index);
}
