// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface AMQPRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.AMQPRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .records.AMQPSinkRecord records = 1;</code>
   */
  java.util.List<sh.batch.events.records.Amqp.AMQPSinkRecord> 
      getRecordsList();
  /**
   * <code>repeated .records.AMQPSinkRecord records = 1;</code>
   */
  sh.batch.events.records.Amqp.AMQPSinkRecord getRecords(int index);
  /**
   * <code>repeated .records.AMQPSinkRecord records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .records.AMQPSinkRecord records = 1;</code>
   */
  java.util.List<? extends sh.batch.events.records.Amqp.AMQPSinkRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .records.AMQPSinkRecord records = 1;</code>
   */
  sh.batch.events.records.Amqp.AMQPSinkRecordOrBuilder getRecordsOrBuilder(
      int index);
}
