// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface GenericRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.GenericRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .records.GenericRecord records = 1;</code>
   */
  java.util.List<sh.batch.events.records.Generic.GenericRecord> 
      getRecordsList();
  /**
   * <code>repeated .records.GenericRecord records = 1;</code>
   */
  sh.batch.events.records.Generic.GenericRecord getRecords(int index);
  /**
   * <code>repeated .records.GenericRecord records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .records.GenericRecord records = 1;</code>
   */
  java.util.List<? extends sh.batch.events.records.Generic.GenericRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .records.GenericRecord records = 1;</code>
   */
  sh.batch.events.records.Generic.GenericRecordOrBuilder getRecordsOrBuilder(
      int index);
}
