// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public final class GrpcCollector {
  private GrpcCollector() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_AddRecordsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_AddRecordsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_AddRecordsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_AddRecordsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024grpc-collector.proto\022\010services\032\023events" +
      "/status.proto\032\032events/records/kafka.prot" +
      "o\"E\n\021AddRecordsRequest\0220\n\007records\030\001 \003(\0132" +
      "\037.events.records.KafkaSinkRecord\"S\n\022AddR" +
      "ecordsResponse\022\035\n\025num_records_processed\030" +
      "\001 \001(\003\022\036\n\006status\030\002 \001(\0132\016.events.Status2X\n" +
      "\rGRPCCollector\022G\n\nAddRecords\022\033.services." +
      "AddRecordsRequest\032\034.services.AddRecordsR" +
      "esponseB\025\n\021sh.batch.servicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          sh.batch.events.ResponseStatus.getDescriptor(),
          sh.batch.events.records.Kafka.getDescriptor(),
        }, assigner);
    internal_static_services_AddRecordsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_AddRecordsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_AddRecordsRequest_descriptor,
        new java.lang.String[] { "Records", });
    internal_static_services_AddRecordsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_AddRecordsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_AddRecordsResponse_descriptor,
        new java.lang.String[] { "NumRecordsProcessed", "Status", });
    sh.batch.events.ResponseStatus.getDescriptor();
    sh.batch.events.records.Kafka.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
