// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface KafkaSinkRecordResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.KafkaSinkRecordResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 num_records_processed = 1;</code>
   */
  long getNumRecordsProcessed();

  /**
   * <code>.events.Status status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>.events.Status status = 2;</code>
   */
  sh.batch.events.ResponseStatus.Status getStatus();
  /**
   * <code>.events.Status status = 2;</code>
   */
  sh.batch.events.ResponseStatus.StatusOrBuilder getStatusOrBuilder();
}
