// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface SQSRecordRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.SQSRecordRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .records.SQSRecord records = 1;</code>
   */
  java.util.List<sh.batch.events.records.Sqs.SQSRecord> 
      getRecordsList();
  /**
   * <code>repeated .records.SQSRecord records = 1;</code>
   */
  sh.batch.events.records.Sqs.SQSRecord getRecords(int index);
  /**
   * <code>repeated .records.SQSRecord records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .records.SQSRecord records = 1;</code>
   */
  java.util.List<? extends sh.batch.events.records.Sqs.SQSRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .records.SQSRecord records = 1;</code>
   */
  sh.batch.events.records.Sqs.SQSRecordOrBuilder getRecordsOrBuilder(
      int index);
}
