// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.events.Status status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.events.Status status = 1;</code>
   */
  sh.batch.events.ResponseStatus.Status getStatus();
  /**
   * <code>.events.Status status = 1;</code>
   */
  sh.batch.events.ResponseStatus.StatusOrBuilder getStatusOrBuilder();
}
