// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc-collector.proto

package sh.batch.services;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.TestRequest)
    com.google.protobuf.MessageOrBuilder {
}
