// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: records/amqp.proto

package sh.batch.events.records;

public final class Amqp {
  private Amqp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AMQPSinkRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:records.AMQPSinkRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes body = 1;</code>
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <code>int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>string type = 3;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string exchange = 4;</code>
     */
    java.lang.String getExchange();
    /**
     * <code>string exchange = 4;</code>
     */
    com.google.protobuf.ByteString
        getExchangeBytes();

    /**
     * <code>string routing_key = 5;</code>
     */
    java.lang.String getRoutingKey();
    /**
     * <code>string routing_key = 5;</code>
     */
    com.google.protobuf.ByteString
        getRoutingKeyBytes();

    /**
     * <code>string content_type = 6;</code>
     */
    java.lang.String getContentType();
    /**
     * <code>string content_type = 6;</code>
     */
    com.google.protobuf.ByteString
        getContentTypeBytes();

    /**
     * <code>string content_encoding = 7;</code>
     */
    java.lang.String getContentEncoding();
    /**
     * <code>string content_encoding = 7;</code>
     */
    com.google.protobuf.ByteString
        getContentEncodingBytes();

    /**
     * <code>int32 priority = 8;</code>
     */
    int getPriority();

    /**
     * <code>string expiration = 9;</code>
     */
    java.lang.String getExpiration();
    /**
     * <code>string expiration = 9;</code>
     */
    com.google.protobuf.ByteString
        getExpirationBytes();

    /**
     * <code>string message_id = 10;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>string message_id = 10;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string user_id = 11;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 11;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string app_id = 12;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string app_id = 12;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string reply_to = 13;</code>
     */
    java.lang.String getReplyTo();
    /**
     * <code>string reply_to = 13;</code>
     */
    com.google.protobuf.ByteString
        getReplyToBytes();

    /**
     * <code>string correlation_id = 14;</code>
     */
    java.lang.String getCorrelationId();
    /**
     * <code>string correlation_id = 14;</code>
     */
    com.google.protobuf.ByteString
        getCorrelationIdBytes();
  }
  /**
   * <pre>
   * See: https://godoc.org/github.com/streadway/amqp#Delivery
   * </pre>
   *
   * Protobuf type {@code records.AMQPSinkRecord}
   */
  public  static final class AMQPSinkRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:records.AMQPSinkRecord)
      AMQPSinkRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AMQPSinkRecord.newBuilder() to construct.
    private AMQPSinkRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AMQPSinkRecord() {
      body_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      type_ = "";
      exchange_ = "";
      routingKey_ = "";
      contentType_ = "";
      contentEncoding_ = "";
      priority_ = 0;
      expiration_ = "";
      messageId_ = "";
      userId_ = "";
      appId_ = "";
      replyTo_ = "";
      correlationId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AMQPSinkRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              body_ = input.readBytes();
              break;
            }
            case 16: {

              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              exchange_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              routingKey_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              contentType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              contentEncoding_ = s;
              break;
            }
            case 64: {

              priority_ = input.readInt32();
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              expiration_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              replyTo_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              correlationId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sh.batch.events.records.Amqp.internal_static_records_AMQPSinkRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sh.batch.events.records.Amqp.internal_static_records_AMQPSinkRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sh.batch.events.records.Amqp.AMQPSinkRecord.class, sh.batch.events.records.Amqp.AMQPSinkRecord.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 1;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 3;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXCHANGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object exchange_;
    /**
     * <code>string exchange = 4;</code>
     */
    public java.lang.String getExchange() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exchange_ = s;
        return s;
      }
    }
    /**
     * <code>string exchange = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExchangeBytes() {
      java.lang.Object ref = exchange_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exchange_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROUTING_KEY_FIELD_NUMBER = 5;
    private volatile java.lang.Object routingKey_;
    /**
     * <code>string routing_key = 5;</code>
     */
    public java.lang.String getRoutingKey() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        routingKey_ = s;
        return s;
      }
    }
    /**
     * <code>string routing_key = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRoutingKeyBytes() {
      java.lang.Object ref = routingKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        routingKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object contentType_;
    /**
     * <code>string content_type = 6;</code>
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      }
    }
    /**
     * <code>string content_type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_ENCODING_FIELD_NUMBER = 7;
    private volatile java.lang.Object contentEncoding_;
    /**
     * <code>string content_encoding = 7;</code>
     */
    public java.lang.String getContentEncoding() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentEncoding_ = s;
        return s;
      }
    }
    /**
     * <code>string content_encoding = 7;</code>
     */
    public com.google.protobuf.ByteString
        getContentEncodingBytes() {
      java.lang.Object ref = contentEncoding_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentEncoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 8;
    private int priority_;
    /**
     * <code>int32 priority = 8;</code>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int EXPIRATION_FIELD_NUMBER = 9;
    private volatile java.lang.Object expiration_;
    /**
     * <code>string expiration = 9;</code>
     */
    public java.lang.String getExpiration() {
      java.lang.Object ref = expiration_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        expiration_ = s;
        return s;
      }
    }
    /**
     * <code>string expiration = 9;</code>
     */
    public com.google.protobuf.ByteString
        getExpirationBytes() {
      java.lang.Object ref = expiration_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        expiration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 10;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string message_id = 10;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string message_id = 10;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 11;
    private volatile java.lang.Object userId_;
    /**
     * <code>string user_id = 11;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 11;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APP_ID_FIELD_NUMBER = 12;
    private volatile java.lang.Object appId_;
    /**
     * <code>string app_id = 12;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string app_id = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPLY_TO_FIELD_NUMBER = 13;
    private volatile java.lang.Object replyTo_;
    /**
     * <code>string reply_to = 13;</code>
     */
    public java.lang.String getReplyTo() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyTo_ = s;
        return s;
      }
    }
    /**
     * <code>string reply_to = 13;</code>
     */
    public com.google.protobuf.ByteString
        getReplyToBytes() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 14;
    private volatile java.lang.Object correlationId_;
    /**
     * <code>string correlation_id = 14;</code>
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      }
    }
    /**
     * <code>string correlation_id = 14;</code>
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!body_.isEmpty()) {
        output.writeBytes(1, body_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!getExchangeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, exchange_);
      }
      if (!getRoutingKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, routingKey_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, contentType_);
      }
      if (!getContentEncodingBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contentEncoding_);
      }
      if (priority_ != 0) {
        output.writeInt32(8, priority_);
      }
      if (!getExpirationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, expiration_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, messageId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, userId_);
      }
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, appId_);
      }
      if (!getReplyToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, replyTo_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, correlationId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, body_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!getExchangeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, exchange_);
      }
      if (!getRoutingKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, routingKey_);
      }
      if (!getContentTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, contentType_);
      }
      if (!getContentEncodingBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contentEncoding_);
      }
      if (priority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, priority_);
      }
      if (!getExpirationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, expiration_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, messageId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, userId_);
      }
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, appId_);
      }
      if (!getReplyToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, replyTo_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, correlationId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sh.batch.events.records.Amqp.AMQPSinkRecord)) {
        return super.equals(obj);
      }
      sh.batch.events.records.Amqp.AMQPSinkRecord other = (sh.batch.events.records.Amqp.AMQPSinkRecord) obj;

      boolean result = true;
      result = result && getBody()
          .equals(other.getBody());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getType()
          .equals(other.getType());
      result = result && getExchange()
          .equals(other.getExchange());
      result = result && getRoutingKey()
          .equals(other.getRoutingKey());
      result = result && getContentType()
          .equals(other.getContentType());
      result = result && getContentEncoding()
          .equals(other.getContentEncoding());
      result = result && (getPriority()
          == other.getPriority());
      result = result && getExpiration()
          .equals(other.getExpiration());
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && getReplyTo()
          .equals(other.getReplyTo());
      result = result && getCorrelationId()
          .equals(other.getCorrelationId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + EXCHANGE_FIELD_NUMBER;
      hash = (53 * hash) + getExchange().hashCode();
      hash = (37 * hash) + ROUTING_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getRoutingKey().hashCode();
      hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContentType().hashCode();
      hash = (37 * hash) + CONTENT_ENCODING_FIELD_NUMBER;
      hash = (53 * hash) + getContentEncoding().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
      hash = (37 * hash) + EXPIRATION_FIELD_NUMBER;
      hash = (53 * hash) + getExpiration().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + APP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + REPLY_TO_FIELD_NUMBER;
      hash = (53 * hash) + getReplyTo().hashCode();
      hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Amqp.AMQPSinkRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sh.batch.events.records.Amqp.AMQPSinkRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * See: https://godoc.org/github.com/streadway/amqp#Delivery
     * </pre>
     *
     * Protobuf type {@code records.AMQPSinkRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:records.AMQPSinkRecord)
        sh.batch.events.records.Amqp.AMQPSinkRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sh.batch.events.records.Amqp.internal_static_records_AMQPSinkRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sh.batch.events.records.Amqp.internal_static_records_AMQPSinkRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sh.batch.events.records.Amqp.AMQPSinkRecord.class, sh.batch.events.records.Amqp.AMQPSinkRecord.Builder.class);
      }

      // Construct using sh.batch.events.records.Amqp.AMQPSinkRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        body_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        type_ = "";

        exchange_ = "";

        routingKey_ = "";

        contentType_ = "";

        contentEncoding_ = "";

        priority_ = 0;

        expiration_ = "";

        messageId_ = "";

        userId_ = "";

        appId_ = "";

        replyTo_ = "";

        correlationId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sh.batch.events.records.Amqp.internal_static_records_AMQPSinkRecord_descriptor;
      }

      public sh.batch.events.records.Amqp.AMQPSinkRecord getDefaultInstanceForType() {
        return sh.batch.events.records.Amqp.AMQPSinkRecord.getDefaultInstance();
      }

      public sh.batch.events.records.Amqp.AMQPSinkRecord build() {
        sh.batch.events.records.Amqp.AMQPSinkRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sh.batch.events.records.Amqp.AMQPSinkRecord buildPartial() {
        sh.batch.events.records.Amqp.AMQPSinkRecord result = new sh.batch.events.records.Amqp.AMQPSinkRecord(this);
        result.body_ = body_;
        result.timestamp_ = timestamp_;
        result.type_ = type_;
        result.exchange_ = exchange_;
        result.routingKey_ = routingKey_;
        result.contentType_ = contentType_;
        result.contentEncoding_ = contentEncoding_;
        result.priority_ = priority_;
        result.expiration_ = expiration_;
        result.messageId_ = messageId_;
        result.userId_ = userId_;
        result.appId_ = appId_;
        result.replyTo_ = replyTo_;
        result.correlationId_ = correlationId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sh.batch.events.records.Amqp.AMQPSinkRecord) {
          return mergeFrom((sh.batch.events.records.Amqp.AMQPSinkRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sh.batch.events.records.Amqp.AMQPSinkRecord other) {
        if (other == sh.batch.events.records.Amqp.AMQPSinkRecord.getDefaultInstance()) return this;
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getExchange().isEmpty()) {
          exchange_ = other.exchange_;
          onChanged();
        }
        if (!other.getRoutingKey().isEmpty()) {
          routingKey_ = other.routingKey_;
          onChanged();
        }
        if (!other.getContentType().isEmpty()) {
          contentType_ = other.contentType_;
          onChanged();
        }
        if (!other.getContentEncoding().isEmpty()) {
          contentEncoding_ = other.contentEncoding_;
          onChanged();
        }
        if (other.getPriority() != 0) {
          setPriority(other.getPriority());
        }
        if (!other.getExpiration().isEmpty()) {
          expiration_ = other.expiration_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getReplyTo().isEmpty()) {
          replyTo_ = other.replyTo_;
          onChanged();
        }
        if (!other.getCorrelationId().isEmpty()) {
          correlationId_ = other.correlationId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sh.batch.events.records.Amqp.AMQPSinkRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sh.batch.events.records.Amqp.AMQPSinkRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 1;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 1;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 1;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 3;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object exchange_ = "";
      /**
       * <code>string exchange = 4;</code>
       */
      public java.lang.String getExchange() {
        java.lang.Object ref = exchange_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exchange_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exchange = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExchangeBytes() {
        java.lang.Object ref = exchange_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exchange_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exchange = 4;</code>
       */
      public Builder setExchange(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        exchange_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 4;</code>
       */
      public Builder clearExchange() {
        
        exchange_ = getDefaultInstance().getExchange();
        onChanged();
        return this;
      }
      /**
       * <code>string exchange = 4;</code>
       */
      public Builder setExchangeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        exchange_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object routingKey_ = "";
      /**
       * <code>string routing_key = 5;</code>
       */
      public java.lang.String getRoutingKey() {
        java.lang.Object ref = routingKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          routingKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string routing_key = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRoutingKeyBytes() {
        java.lang.Object ref = routingKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          routingKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string routing_key = 5;</code>
       */
      public Builder setRoutingKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        routingKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string routing_key = 5;</code>
       */
      public Builder clearRoutingKey() {
        
        routingKey_ = getDefaultInstance().getRoutingKey();
        onChanged();
        return this;
      }
      /**
       * <code>string routing_key = 5;</code>
       */
      public Builder setRoutingKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        routingKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentType_ = "";
      /**
       * <code>string content_type = 6;</code>
       */
      public java.lang.String getContentType() {
        java.lang.Object ref = contentType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content_type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContentTypeBytes() {
        java.lang.Object ref = contentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content_type = 6;</code>
       */
      public Builder setContentType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content_type = 6;</code>
       */
      public Builder clearContentType() {
        
        contentType_ = getDefaultInstance().getContentType();
        onChanged();
        return this;
      }
      /**
       * <code>string content_type = 6;</code>
       */
      public Builder setContentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contentType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contentEncoding_ = "";
      /**
       * <code>string content_encoding = 7;</code>
       */
      public java.lang.String getContentEncoding() {
        java.lang.Object ref = contentEncoding_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contentEncoding_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content_encoding = 7;</code>
       */
      public com.google.protobuf.ByteString
          getContentEncodingBytes() {
        java.lang.Object ref = contentEncoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contentEncoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content_encoding = 7;</code>
       */
      public Builder setContentEncoding(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contentEncoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content_encoding = 7;</code>
       */
      public Builder clearContentEncoding() {
        
        contentEncoding_ = getDefaultInstance().getContentEncoding();
        onChanged();
        return this;
      }
      /**
       * <code>string content_encoding = 7;</code>
       */
      public Builder setContentEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contentEncoding_ = value;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>int32 priority = 8;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>int32 priority = 8;</code>
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priority = 8;</code>
       */
      public Builder clearPriority() {
        
        priority_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object expiration_ = "";
      /**
       * <code>string expiration = 9;</code>
       */
      public java.lang.String getExpiration() {
        java.lang.Object ref = expiration_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          expiration_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string expiration = 9;</code>
       */
      public com.google.protobuf.ByteString
          getExpirationBytes() {
        java.lang.Object ref = expiration_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          expiration_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string expiration = 9;</code>
       */
      public Builder setExpiration(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expiration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string expiration = 9;</code>
       */
      public Builder clearExpiration() {
        
        expiration_ = getDefaultInstance().getExpiration();
        onChanged();
        return this;
      }
      /**
       * <code>string expiration = 9;</code>
       */
      public Builder setExpirationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expiration_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>string message_id = 10;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message_id = 10;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message_id = 10;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 10;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 10;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 11;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 11;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 11;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 11;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 11;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appId_ = "";
      /**
       * <code>string app_id = 12;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string app_id = 12;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string app_id = 12;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string app_id = 12;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string app_id = 12;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object replyTo_ = "";
      /**
       * <code>string reply_to = 13;</code>
       */
      public java.lang.String getReplyTo() {
        java.lang.Object ref = replyTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          replyTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reply_to = 13;</code>
       */
      public com.google.protobuf.ByteString
          getReplyToBytes() {
        java.lang.Object ref = replyTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reply_to = 13;</code>
       */
      public Builder setReplyTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        replyTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reply_to = 13;</code>
       */
      public Builder clearReplyTo() {
        
        replyTo_ = getDefaultInstance().getReplyTo();
        onChanged();
        return this;
      }
      /**
       * <code>string reply_to = 13;</code>
       */
      public Builder setReplyToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        replyTo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object correlationId_ = "";
      /**
       * <code>string correlation_id = 14;</code>
       */
      public java.lang.String getCorrelationId() {
        java.lang.Object ref = correlationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          correlationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string correlation_id = 14;</code>
       */
      public com.google.protobuf.ByteString
          getCorrelationIdBytes() {
        java.lang.Object ref = correlationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correlationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string correlation_id = 14;</code>
       */
      public Builder setCorrelationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 14;</code>
       */
      public Builder clearCorrelationId() {
        
        correlationId_ = getDefaultInstance().getCorrelationId();
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 14;</code>
       */
      public Builder setCorrelationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        correlationId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:records.AMQPSinkRecord)
    }

    // @@protoc_insertion_point(class_scope:records.AMQPSinkRecord)
    private static final sh.batch.events.records.Amqp.AMQPSinkRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sh.batch.events.records.Amqp.AMQPSinkRecord();
    }

    public static sh.batch.events.records.Amqp.AMQPSinkRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AMQPSinkRecord>
        PARSER = new com.google.protobuf.AbstractParser<AMQPSinkRecord>() {
      public AMQPSinkRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AMQPSinkRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AMQPSinkRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AMQPSinkRecord> getParserForType() {
      return PARSER;
    }

    public sh.batch.events.records.Amqp.AMQPSinkRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_records_AMQPSinkRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_records_AMQPSinkRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022records/amqp.proto\022\007records\"\233\002\n\016AMQPSi" +
      "nkRecord\022\014\n\004body\030\001 \001(\014\022\021\n\ttimestamp\030\002 \001(" +
      "\003\022\014\n\004type\030\003 \001(\t\022\020\n\010exchange\030\004 \001(\t\022\023\n\013rou" +
      "ting_key\030\005 \001(\t\022\024\n\014content_type\030\006 \001(\t\022\030\n\020" +
      "content_encoding\030\007 \001(\t\022\020\n\010priority\030\010 \001(\005" +
      "\022\022\n\nexpiration\030\t \001(\t\022\022\n\nmessage_id\030\n \001(\t" +
      "\022\017\n\007user_id\030\013 \001(\t\022\016\n\006app_id\030\014 \001(\t\022\020\n\010rep" +
      "ly_to\030\r \001(\t\022\026\n\016correlation_id\030\016 \001(\tBO\n\027s" +
      "h.batch.events.recordsZ4github.com/batch" +
      "corp/schemas/build/go/events/recordsb\006pr",
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_records_AMQPSinkRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_records_AMQPSinkRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_records_AMQPSinkRecord_descriptor,
        new java.lang.String[] { "Body", "Timestamp", "Type", "Exchange", "RoutingKey", "ContentType", "ContentEncoding", "Priority", "Expiration", "MessageId", "UserId", "AppId", "ReplyTo", "CorrelationId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
