// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: records/sqs.proto

package sh.batch.events.records;

public final class Sqs {
  private Sqs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SQSRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:records.SQSRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */
    boolean containsAttributes(
        java.lang.String key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAttributes();
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAttributesMap();
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    java.lang.String getAttributesOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */
    int getMessageattributesCount();
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */
    boolean containsMessageattributes(
        java.lang.String key);
    /**
     * Use {@link #getMessageattributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
    getMessageattributes();
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */
    java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
    getMessageattributesMap();
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrDefault(
        java.lang.String key,
        sh.batch.events.records.Sqs.SQSRecordMessageAttribute defaultValue);
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrThrow(
        java.lang.String key);

    /**
     * <code>string messageid = 3;</code>
     */
    java.lang.String getMessageid();
    /**
     * <code>string messageid = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageidBytes();

    /**
     * <code>string receipt = 4;</code>
     */
    java.lang.String getReceipt();
    /**
     * <code>string receipt = 4;</code>
     */
    com.google.protobuf.ByteString
        getReceiptBytes();

    /**
     * <code>bytes body = 5;</code>
     */
    com.google.protobuf.ByteString getBody();

    /**
     * <code>int64 timestamp = 6;</code>
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * See: https://godoc.org/github.com/datacratic/aws-sdk-go/service/sqs#Message
   * </pre>
   *
   * Protobuf type {@code records.SQSRecord}
   */
  public  static final class SQSRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:records.SQSRecord)
      SQSRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SQSRecord.newBuilder() to construct.
    private SQSRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SQSRecord() {
      messageid_ = "";
      receipt_ = "";
      body_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SQSRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                attributes_ = com.google.protobuf.MapField.newMapField(
                    AttributesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              attributes__ = input.readMessage(
                  AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attributes_.getMutableMap().put(
                  attributes__.getKey(), attributes__.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                messageattributes_ = com.google.protobuf.MapField.newMapField(
                    MessageattributesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
              messageattributes__ = input.readMessage(
                  MessageattributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              messageattributes_.getMutableMap().put(
                  messageattributes__.getKey(), messageattributes__.getValue());
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              messageid_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              receipt_ = s;
              break;
            }
            case 42: {

              body_ = input.readBytes();
              break;
            }
            case 48: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sh.batch.events.records.Sqs.internal_static_records_SQSRecord_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAttributes();
        case 2:
          return internalGetMessageattributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sh.batch.events.records.Sqs.internal_static_records_SQSRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sh.batch.events.records.Sqs.SQSRecord.class, sh.batch.events.records.Sqs.SQSRecord.Builder.class);
    }

    private int bitField0_;
    public static final int ATTRIBUTES_FIELD_NUMBER = 1;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  sh.batch.events.records.Sqs.internal_static_records_SQSRecord_AttributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> attributes_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }

    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    public java.lang.String getAttributesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attributes = 1;</code>
     */

    public java.lang.String getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MESSAGEATTRIBUTES_FIELD_NUMBER = 2;
    private static final class MessageattributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>newDefaultInstance(
                  sh.batch.events.records.Sqs.internal_static_records_SQSRecord_MessageattributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  sh.batch.events.records.Sqs.SQSRecordMessageAttribute.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> messageattributes_;
    private com.google.protobuf.MapField<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
    internalGetMessageattributes() {
      if (messageattributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MessageattributesDefaultEntryHolder.defaultEntry);
      }
      return messageattributes_;
    }

    public int getMessageattributesCount() {
      return internalGetMessageattributes().getMap().size();
    }
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    public boolean containsMessageattributes(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMessageattributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMessageattributesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> getMessageattributes() {
      return getMessageattributesMap();
    }
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    public java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> getMessageattributesMap() {
      return internalGetMessageattributes().getMap();
    }
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrDefault(
        java.lang.String key,
        sh.batch.events.records.Sqs.SQSRecordMessageAttribute defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> map =
          internalGetMessageattributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
     */

    public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> map =
          internalGetMessageattributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MESSAGEID_FIELD_NUMBER = 3;
    private volatile java.lang.Object messageid_;
    /**
     * <code>string messageid = 3;</code>
     */
    public java.lang.String getMessageid() {
      java.lang.Object ref = messageid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageid_ = s;
        return s;
      }
    }
    /**
     * <code>string messageid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageidBytes() {
      java.lang.Object ref = messageid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIPT_FIELD_NUMBER = 4;
    private volatile java.lang.Object receipt_;
    /**
     * <code>string receipt = 4;</code>
     */
    public java.lang.String getReceipt() {
      java.lang.Object ref = receipt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receipt_ = s;
        return s;
      }
    }
    /**
     * <code>string receipt = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReceiptBytes() {
      java.lang.Object ref = receipt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receipt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 5;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 6;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMessageattributes(),
          MessageattributesDefaultEntryHolder.defaultEntry,
          2);
      if (!getMessageidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageid_);
      }
      if (!getReceiptBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, receipt_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(5, body_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(6, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, attributes__);
      }
      for (java.util.Map.Entry<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> entry
           : internalGetMessageattributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
        messageattributes__ = MessageattributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, messageattributes__);
      }
      if (!getMessageidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageid_);
      }
      if (!getReceiptBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, receipt_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, body_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sh.batch.events.records.Sqs.SQSRecord)) {
        return super.equals(obj);
      }
      sh.batch.events.records.Sqs.SQSRecord other = (sh.batch.events.records.Sqs.SQSRecord) obj;

      boolean result = true;
      result = result && internalGetAttributes().equals(
          other.internalGetAttributes());
      result = result && internalGetMessageattributes().equals(
          other.internalGetMessageattributes());
      result = result && getMessageid()
          .equals(other.getMessageid());
      result = result && getReceipt()
          .equals(other.getReceipt());
      result = result && getBody()
          .equals(other.getBody());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      if (!internalGetMessageattributes().getMap().isEmpty()) {
        hash = (37 * hash) + MESSAGEATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMessageattributes().hashCode();
      }
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageid().hashCode();
      hash = (37 * hash) + RECEIPT_FIELD_NUMBER;
      hash = (53 * hash) + getReceipt().hashCode();
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sh.batch.events.records.Sqs.SQSRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * See: https://godoc.org/github.com/datacratic/aws-sdk-go/service/sqs#Message
     * </pre>
     *
     * Protobuf type {@code records.SQSRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:records.SQSRecord)
        sh.batch.events.records.Sqs.SQSRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecord_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAttributes();
          case 2:
            return internalGetMessageattributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableAttributes();
          case 2:
            return internalGetMutableMessageattributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sh.batch.events.records.Sqs.SQSRecord.class, sh.batch.events.records.Sqs.SQSRecord.Builder.class);
      }

      // Construct using sh.batch.events.records.Sqs.SQSRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableAttributes().clear();
        internalGetMutableMessageattributes().clear();
        messageid_ = "";

        receipt_ = "";

        body_ = com.google.protobuf.ByteString.EMPTY;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecord_descriptor;
      }

      public sh.batch.events.records.Sqs.SQSRecord getDefaultInstanceForType() {
        return sh.batch.events.records.Sqs.SQSRecord.getDefaultInstance();
      }

      public sh.batch.events.records.Sqs.SQSRecord build() {
        sh.batch.events.records.Sqs.SQSRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sh.batch.events.records.Sqs.SQSRecord buildPartial() {
        sh.batch.events.records.Sqs.SQSRecord result = new sh.batch.events.records.Sqs.SQSRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.attributes_ = internalGetAttributes();
        result.attributes_.makeImmutable();
        result.messageattributes_ = internalGetMessageattributes();
        result.messageattributes_.makeImmutable();
        result.messageid_ = messageid_;
        result.receipt_ = receipt_;
        result.body_ = body_;
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sh.batch.events.records.Sqs.SQSRecord) {
          return mergeFrom((sh.batch.events.records.Sqs.SQSRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sh.batch.events.records.Sqs.SQSRecord other) {
        if (other == sh.batch.events.records.Sqs.SQSRecord.getDefaultInstance()) return this;
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        internalGetMutableMessageattributes().mergeFrom(
            other.internalGetMessageattributes());
        if (!other.getMessageid().isEmpty()) {
          messageid_ = other.messageid_;
          onChanged();
        }
        if (!other.getReceipt().isEmpty()) {
          receipt_ = other.receipt_;
          onChanged();
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sh.batch.events.records.Sqs.SQSRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sh.batch.events.records.Sqs.SQSRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attributes_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAttributes() {
        if (attributes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        return attributes_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAttributes() {
        onChanged();;
        if (attributes_ == null) {
          attributes_ = com.google.protobuf.MapField.newMapField(
              AttributesDefaultEntryHolder.defaultEntry);
        }
        if (!attributes_.isMutable()) {
          attributes_ = attributes_.copy();
        }
        return attributes_;
      }

      public int getAttributesCount() {
        return internalGetAttributes().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public boolean containsAttributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttributes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAttributesMap() {
        return internalGetAttributes().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public java.lang.String getAttributesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public java.lang.String getAttributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttributes() {
        internalGetMutableAttributes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public Builder removeAttributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttributes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAttributes() {
        return internalGetMutableAttributes().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */
      public Builder putAttributes(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttributes().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attributes = 1;</code>
       */

      public Builder putAllAttributes(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAttributes().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> messageattributes_;
      private com.google.protobuf.MapField<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
      internalGetMessageattributes() {
        if (messageattributes_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MessageattributesDefaultEntryHolder.defaultEntry);
        }
        return messageattributes_;
      }
      private com.google.protobuf.MapField<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
      internalGetMutableMessageattributes() {
        onChanged();;
        if (messageattributes_ == null) {
          messageattributes_ = com.google.protobuf.MapField.newMapField(
              MessageattributesDefaultEntryHolder.defaultEntry);
        }
        if (!messageattributes_.isMutable()) {
          messageattributes_ = messageattributes_.copy();
        }
        return messageattributes_;
      }

      public int getMessageattributesCount() {
        return internalGetMessageattributes().getMap().size();
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public boolean containsMessageattributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMessageattributes().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMessageattributesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> getMessageattributes() {
        return getMessageattributesMap();
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> getMessageattributesMap() {
        return internalGetMessageattributes().getMap();
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrDefault(
          java.lang.String key,
          sh.batch.events.records.Sqs.SQSRecordMessageAttribute defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> map =
            internalGetMessageattributes().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getMessageattributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> map =
            internalGetMessageattributes().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMessageattributes() {
        internalGetMutableMessageattributes().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public Builder removeMessageattributes(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMessageattributes().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute>
      getMutableMessageattributes() {
        return internalGetMutableMessageattributes().getMutableMap();
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */
      public Builder putMessageattributes(
          java.lang.String key,
          sh.batch.events.records.Sqs.SQSRecordMessageAttribute value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMessageattributes().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .records.SQSRecordMessageAttribute&gt; messageattributes = 2;</code>
       */

      public Builder putAllMessageattributes(
          java.util.Map<java.lang.String, sh.batch.events.records.Sqs.SQSRecordMessageAttribute> values) {
        internalGetMutableMessageattributes().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object messageid_ = "";
      /**
       * <code>string messageid = 3;</code>
       */
      public java.lang.String getMessageid() {
        java.lang.Object ref = messageid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageid = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageidBytes() {
        java.lang.Object ref = messageid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageid = 3;</code>
       */
      public Builder setMessageid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageid = 3;</code>
       */
      public Builder clearMessageid() {
        
        messageid_ = getDefaultInstance().getMessageid();
        onChanged();
        return this;
      }
      /**
       * <code>string messageid = 3;</code>
       */
      public Builder setMessageidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receipt_ = "";
      /**
       * <code>string receipt = 4;</code>
       */
      public java.lang.String getReceipt() {
        java.lang.Object ref = receipt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receipt_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receipt = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReceiptBytes() {
        java.lang.Object ref = receipt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receipt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receipt = 4;</code>
       */
      public Builder setReceipt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receipt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receipt = 4;</code>
       */
      public Builder clearReceipt() {
        
        receipt_ = getDefaultInstance().getReceipt();
        onChanged();
        return this;
      }
      /**
       * <code>string receipt = 4;</code>
       */
      public Builder setReceiptBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receipt_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 5;</code>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 5;</code>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 5;</code>
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:records.SQSRecord)
    }

    // @@protoc_insertion_point(class_scope:records.SQSRecord)
    private static final sh.batch.events.records.Sqs.SQSRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sh.batch.events.records.Sqs.SQSRecord();
    }

    public static sh.batch.events.records.Sqs.SQSRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SQSRecord>
        PARSER = new com.google.protobuf.AbstractParser<SQSRecord>() {
      public SQSRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SQSRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SQSRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SQSRecord> getParserForType() {
      return PARSER;
    }

    public sh.batch.events.records.Sqs.SQSRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SQSRecordMessageAttributeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:records.SQSRecordMessageAttribute)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string datatype = 1;</code>
     */
    java.lang.String getDatatype();
    /**
     * <code>string datatype = 1;</code>
     */
    com.google.protobuf.ByteString
        getDatatypeBytes();

    /**
     * <code>string stringvalue = 2;</code>
     */
    java.lang.String getStringvalue();
    /**
     * <code>string stringvalue = 2;</code>
     */
    com.google.protobuf.ByteString
        getStringvalueBytes();

    /**
     * <code>bytes binaryvalue = 3;</code>
     */
    com.google.protobuf.ByteString getBinaryvalue();
  }
  /**
   * Protobuf type {@code records.SQSRecordMessageAttribute}
   */
  public  static final class SQSRecordMessageAttribute extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:records.SQSRecordMessageAttribute)
      SQSRecordMessageAttributeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SQSRecordMessageAttribute.newBuilder() to construct.
    private SQSRecordMessageAttribute(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SQSRecordMessageAttribute() {
      datatype_ = "";
      stringvalue_ = "";
      binaryvalue_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SQSRecordMessageAttribute(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              datatype_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              stringvalue_ = s;
              break;
            }
            case 26: {

              binaryvalue_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sh.batch.events.records.Sqs.internal_static_records_SQSRecordMessageAttribute_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sh.batch.events.records.Sqs.internal_static_records_SQSRecordMessageAttribute_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sh.batch.events.records.Sqs.SQSRecordMessageAttribute.class, sh.batch.events.records.Sqs.SQSRecordMessageAttribute.Builder.class);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object datatype_;
    /**
     * <code>string datatype = 1;</code>
     */
    public java.lang.String getDatatype() {
      java.lang.Object ref = datatype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datatype_ = s;
        return s;
      }
    }
    /**
     * <code>string datatype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDatatypeBytes() {
      java.lang.Object ref = datatype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datatype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STRINGVALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object stringvalue_;
    /**
     * <code>string stringvalue = 2;</code>
     */
    public java.lang.String getStringvalue() {
      java.lang.Object ref = stringvalue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stringvalue_ = s;
        return s;
      }
    }
    /**
     * <code>string stringvalue = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStringvalueBytes() {
      java.lang.Object ref = stringvalue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stringvalue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BINARYVALUE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString binaryvalue_;
    /**
     * <code>bytes binaryvalue = 3;</code>
     */
    public com.google.protobuf.ByteString getBinaryvalue() {
      return binaryvalue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDatatypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, datatype_);
      }
      if (!getStringvalueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringvalue_);
      }
      if (!binaryvalue_.isEmpty()) {
        output.writeBytes(3, binaryvalue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDatatypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, datatype_);
      }
      if (!getStringvalueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringvalue_);
      }
      if (!binaryvalue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, binaryvalue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sh.batch.events.records.Sqs.SQSRecordMessageAttribute)) {
        return super.equals(obj);
      }
      sh.batch.events.records.Sqs.SQSRecordMessageAttribute other = (sh.batch.events.records.Sqs.SQSRecordMessageAttribute) obj;

      boolean result = true;
      result = result && getDatatype()
          .equals(other.getDatatype());
      result = result && getStringvalue()
          .equals(other.getStringvalue());
      result = result && getBinaryvalue()
          .equals(other.getBinaryvalue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDatatype().hashCode();
      hash = (37 * hash) + STRINGVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringvalue().hashCode();
      hash = (37 * hash) + BINARYVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getBinaryvalue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sh.batch.events.records.Sqs.SQSRecordMessageAttribute prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code records.SQSRecordMessageAttribute}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:records.SQSRecordMessageAttribute)
        sh.batch.events.records.Sqs.SQSRecordMessageAttributeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecordMessageAttribute_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecordMessageAttribute_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sh.batch.events.records.Sqs.SQSRecordMessageAttribute.class, sh.batch.events.records.Sqs.SQSRecordMessageAttribute.Builder.class);
      }

      // Construct using sh.batch.events.records.Sqs.SQSRecordMessageAttribute.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        datatype_ = "";

        stringvalue_ = "";

        binaryvalue_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sh.batch.events.records.Sqs.internal_static_records_SQSRecordMessageAttribute_descriptor;
      }

      public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getDefaultInstanceForType() {
        return sh.batch.events.records.Sqs.SQSRecordMessageAttribute.getDefaultInstance();
      }

      public sh.batch.events.records.Sqs.SQSRecordMessageAttribute build() {
        sh.batch.events.records.Sqs.SQSRecordMessageAttribute result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public sh.batch.events.records.Sqs.SQSRecordMessageAttribute buildPartial() {
        sh.batch.events.records.Sqs.SQSRecordMessageAttribute result = new sh.batch.events.records.Sqs.SQSRecordMessageAttribute(this);
        result.datatype_ = datatype_;
        result.stringvalue_ = stringvalue_;
        result.binaryvalue_ = binaryvalue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sh.batch.events.records.Sqs.SQSRecordMessageAttribute) {
          return mergeFrom((sh.batch.events.records.Sqs.SQSRecordMessageAttribute)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sh.batch.events.records.Sqs.SQSRecordMessageAttribute other) {
        if (other == sh.batch.events.records.Sqs.SQSRecordMessageAttribute.getDefaultInstance()) return this;
        if (!other.getDatatype().isEmpty()) {
          datatype_ = other.datatype_;
          onChanged();
        }
        if (!other.getStringvalue().isEmpty()) {
          stringvalue_ = other.stringvalue_;
          onChanged();
        }
        if (other.getBinaryvalue() != com.google.protobuf.ByteString.EMPTY) {
          setBinaryvalue(other.getBinaryvalue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sh.batch.events.records.Sqs.SQSRecordMessageAttribute parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sh.batch.events.records.Sqs.SQSRecordMessageAttribute) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object datatype_ = "";
      /**
       * <code>string datatype = 1;</code>
       */
      public java.lang.String getDatatype() {
        java.lang.Object ref = datatype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          datatype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string datatype = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDatatypeBytes() {
        java.lang.Object ref = datatype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          datatype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string datatype = 1;</code>
       */
      public Builder setDatatype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        datatype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string datatype = 1;</code>
       */
      public Builder clearDatatype() {
        
        datatype_ = getDefaultInstance().getDatatype();
        onChanged();
        return this;
      }
      /**
       * <code>string datatype = 1;</code>
       */
      public Builder setDatatypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        datatype_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object stringvalue_ = "";
      /**
       * <code>string stringvalue = 2;</code>
       */
      public java.lang.String getStringvalue() {
        java.lang.Object ref = stringvalue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          stringvalue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string stringvalue = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringvalueBytes() {
        java.lang.Object ref = stringvalue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stringvalue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string stringvalue = 2;</code>
       */
      public Builder setStringvalue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stringvalue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string stringvalue = 2;</code>
       */
      public Builder clearStringvalue() {
        
        stringvalue_ = getDefaultInstance().getStringvalue();
        onChanged();
        return this;
      }
      /**
       * <code>string stringvalue = 2;</code>
       */
      public Builder setStringvalueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        stringvalue_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString binaryvalue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes binaryvalue = 3;</code>
       */
      public com.google.protobuf.ByteString getBinaryvalue() {
        return binaryvalue_;
      }
      /**
       * <code>bytes binaryvalue = 3;</code>
       */
      public Builder setBinaryvalue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        binaryvalue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes binaryvalue = 3;</code>
       */
      public Builder clearBinaryvalue() {
        
        binaryvalue_ = getDefaultInstance().getBinaryvalue();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:records.SQSRecordMessageAttribute)
    }

    // @@protoc_insertion_point(class_scope:records.SQSRecordMessageAttribute)
    private static final sh.batch.events.records.Sqs.SQSRecordMessageAttribute DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sh.batch.events.records.Sqs.SQSRecordMessageAttribute();
    }

    public static sh.batch.events.records.Sqs.SQSRecordMessageAttribute getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SQSRecordMessageAttribute>
        PARSER = new com.google.protobuf.AbstractParser<SQSRecordMessageAttribute>() {
      public SQSRecordMessageAttribute parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SQSRecordMessageAttribute(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SQSRecordMessageAttribute> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SQSRecordMessageAttribute> getParserForType() {
      return PARSER;
    }

    public sh.batch.events.records.Sqs.SQSRecordMessageAttribute getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_records_SQSRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_records_SQSRecord_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_records_SQSRecord_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_records_SQSRecord_AttributesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_records_SQSRecord_MessageattributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_records_SQSRecord_MessageattributesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_records_SQSRecordMessageAttribute_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_records_SQSRecordMessageAttribute_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021records/sqs.proto\022\007records\"\337\002\n\tSQSReco" +
      "rd\0226\n\nattributes\030\001 \003(\0132\".records.SQSReco" +
      "rd.AttributesEntry\022D\n\021messageattributes\030" +
      "\002 \003(\0132).records.SQSRecord.Messageattribu" +
      "tesEntry\022\021\n\tmessageid\030\003 \001(\t\022\017\n\007receipt\030\004" +
      " \001(\t\022\014\n\004body\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(\003\0321\n" +
      "\017AttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\032\\\n\026MessageattributesEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".records.SQSReco" +
      "rdMessageAttribute:\0028\001\"W\n\031SQSRecordMessa",
      "geAttribute\022\020\n\010datatype\030\001 \001(\t\022\023\n\013stringv" +
      "alue\030\002 \001(\t\022\023\n\013binaryvalue\030\003 \001(\014BO\n\027sh.ba" +
      "tch.events.recordsZ4github.com/batchcorp" +
      "/schemas/build/go/events/recordsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_records_SQSRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_records_SQSRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_records_SQSRecord_descriptor,
        new java.lang.String[] { "Attributes", "Messageattributes", "Messageid", "Receipt", "Body", "Timestamp", });
    internal_static_records_SQSRecord_AttributesEntry_descriptor =
      internal_static_records_SQSRecord_descriptor.getNestedTypes().get(0);
    internal_static_records_SQSRecord_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_records_SQSRecord_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_records_SQSRecord_MessageattributesEntry_descriptor =
      internal_static_records_SQSRecord_descriptor.getNestedTypes().get(1);
    internal_static_records_SQSRecord_MessageattributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_records_SQSRecord_MessageattributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_records_SQSRecordMessageAttribute_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_records_SQSRecordMessageAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_records_SQSRecordMessageAttribute_descriptor,
        new java.lang.String[] { "Datatype", "Stringvalue", "Binaryvalue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
